filter:
    paths:                ["lib/Link/*"]

default_config:
    checkstyle:
        enabled: true
        naming:
            enabled:              true
            local_variable:       ^[a-z][a-zA-Z0-9]*$
            abstract_class_name:  Abstract|Factory$
            utility_class_name:   Utils?$
            constant_name:        ^[A-Z][A-Z0-9_]*$
            property_name:        ^_?[a-z][a-zA-Z0-9]*$
            method_name:          ^(?:_?[a-z]|__)[a-zA-Z0-9]*$
            parameter_name:       ^_?[a-z][a-zA-Z0-9]*$
            interface_name:       ^Link_[A-Z][a-zA-Z0-9]*Interface$
            type_name:            ^[A-Z][a-zA-Z0-9]*$
            exception_name:       ^Link_Exception_[A-Z][a-zA-Z0-9]*$
            isser_method_name:    ^(?:is|has|should|may|supports)

    unreachable_code:
        enabled:              true

    check_access_control:
        enabled:              true

    typo_checks:
        enabled:              true

    check_variables:
        enabled:              true

    suspicious_code:
        enabled:                                 true
        overriding_parameter:                    false
        parameter_multiple_times:                true
        non_existent_class_in_instanceof_check:  true
        non_existent_class_in_catch_clause:      true
        assignment_of_null_return:               true
        non_commented_switch_fallthrough:        true
        non_commented_empty_catch_block:         true
        overriding_private_members:              true
        precedence_in_condition_assignment:      true

    dead_assignments:
        enabled:              true

    verify_php_doc_comments:
        enabled:                           false
        parameters:                        true
        return:                            true
        suggest_more_specific_types:       false
        ask_for_return_if_not_inferrable:  false
        ask_for_param_type_annotation:     false

    loops_must_use_braces:
        enabled: true

    check_usage_context:
        enabled: true
        method_call_on_non_object:
            enabled:              true
            lenient_in_tests:     true
            test_classes:
                - PHPUnit_Framework_TestCase

        foreach:
            value_as_reference:   true
            traversable:          true

        missing_argument:     true
        argument_type_checks: lenient

    simplify_boolean_return:
        enabled: false

    phpunit_checks:
        enabled: false

    psr0_compliance:
        enabled: false

    reflection_checks:
        enabled:              true

    composer_config_check:
        enabled:        true
        publish_checks: true
        level:          warning

    precedence_checks:
        enabled:                  true
        assignment_in_condition:  true
        comparison_of_bit_result: true

    basic_semantic_checks:
        enabled: true

    doc_comment_fixes:
        enabled: false

    reflection_fixes:
        enabled: false

    use_statement_fixes:
        enabled:              true
        remove_unused:        true
        preserve_multiple:    false
        order_alphabetically: false

    fabpot_cs_fixer:
        enabled: true
        level:   all
